apiVersion: apps/v1
kind: Deployment
metadata:
  name: claclo-app
  labels:
    app: claclo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: claclo-app
  template:
    metadata:
      labels:
        app: claclo-app
    spec:
      containers:
      - name: claclo-app
        image: gcr.io/rare-disk-419803/claclo_image:latest3
        ports:
        - containerPort: 80
        env:
        - name: ENV_VAR_NAME
          value: "Value"

---
apiVersion: v1
kind: Service
metadata:
  name: claclo-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: claclo-app
